def choose_category(category_name):
    if category_name == "animals":
        return categories[0]
    elif category_name == "general knowledge" or "generalknowledge":
        return categories[1]
    elif category_name == "sport" or "sports":
        return categories[2]
    elif category_name == "mythology":
        return categories[3]
    elif category_name == "geography":
        return categories[4]


animals = {
    "response_code": 0,
    "results": [
        {"category": "Animals", "type": "boolean", "difficulty": "medium",
         "question": "An octopus can fit through any hole larger than its beak.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "A slug's blood is green.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Rabbits are rodents.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "A flock of crows is known as a homicide.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "A caterpillar has more muscles than humans do.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Cats have whiskers under their legs.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "The Killer Whale is considered a type of dolphin.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Rabbits are carnivores.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "The internet browser Firefox is named after the Red Panda.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]}

general_knowledge = {
    "response_code": 0,
    "results": [
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Typewriter&quot; is the longest "
                     "word that can be typed using only the first row on a QWERTY keyboard.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Sun rises from the North.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "In 2010, Twitter and the United States Library "
                     "of Congress partnered together to archive every tweet by American citizens.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The French word to travel is &quot;Travail&quot;", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Pluto is a planet.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Albert Einstein had trouble with mathematics when he was in school.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Ping-Pong originated in England", "correct_answer": "True",
         "incorrect_answers": ["False"]}]}
sports = {
    "response_code": 0,
    "results": [
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Peyton Manning retired after winning Super Bowl XLIX.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "The Olympics tennis court is a giant green screen.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Roger Federer is a famous soccer player.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "There are a total of 20 races in Formula One 2016 season.",
         "correct_answer": "False", "incorrect_answers": ["True"]}]}

mythology = {
    "response_code": 0,
    "results": [
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "In Norse mythology, Thor once dressed as a woman.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "According to Greek Mythology, Zeus can control lightning.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "medium",
         "question": "According to Norse mythology, Loki is a mother.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "medium",
         "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "hard",
         "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "medium",
         "question": "In Greek mythology, Hera is the goddess of harvest.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "According to Greek Mythology, Atlas was an Olympian God.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "medium",
         "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "A wyvern is the same as a dragon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "hard",
         "question": "Janus was the Roman god of doorways and passageways.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]}

geography = {"response_code": 0,
             "results": [
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Seoul is the capital of North Korea.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "San Marino is the only country completely surrounded by another country.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "There exists an island named &quot;Java&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Toronto is the capital city of the North American country of Canada.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The Sonoran Desert is located in eastern Africa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Japan has left-hand side traffic.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Norway has a larger land area than Sweden.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Rhode Island is actually located on the US mainland, despite its name.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]}

categories = [animals, general_knowledge, sports, mythology, geography]
